# Generated by Django 2.1.2 on 2018-10-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
