# Generated by Django 2.1.3 on 2018-12-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('tickets', '0002_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Bill'),
        ),
    ]
