# Generated by Django 2.1.3 on 2018-12-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20181210_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
