# Generated by Django 2.1.2 on 2018-11-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20181106_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='docfile',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
